### ISSUE TITLE
Failed host lookup: while using dart frog.

### ISSUE THREAD

**Issue by guccisekspir** [invertase/dart_firebase_admin#6]
Hello,

I was trying to implement dart firebase admin library to my dart:frog library. It is successfully initializing but when I try to do anything related firestore I get 
`Failed host lookup: 'metadata.google.internal'`

I dont have any logic I am just calling on main.

```
Future<FirebaseAdminApp> init(InternetAddress ip, int port) async {
  final admin = FirebaseAdminApp.initializeApp(
    'gizemlikutucom',
    // This will obtain authentication informations from the environment
    Credential.fromApplicationDefaultCredentials(),
  );

  return admin;
}

Future<HttpServer> run(Handler handler, InternetAddress ip, int port) async {
  FirebaseAdminApp admin = await init(ip, port);

  try {
    final firestore = Firestore(admin);
    DocumentSnapshot a = await firestore.collection("a").doc("b").get();

    print(a.data());
  } catch (e) {
    print(e);
  }

  return serve(handler, ip, port);
}
```

here the versions

```
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_firebase_admin: ^0.0.2
  dart_frog: ^1.0.0
  shelf_cors_headers: ^0.1.5
```
